name: Deploy to Clojars

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

    - name: Debug Environment Variables
      run: |
        if [ -z "$CLOJARS_USER" ]; then echo "CLOJARS_USERNAME is not set"; exit 1; fi
        if [ -z "$CLOJARS_PASS" ]; then echo "CLOJARS_PASSWORD is not set"; exit 1; fi
        echo "Environment variables are set correctly."
      env:
        CLOJARS_USER: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASS: ${{ secrets.CLOJARS_PASSWORD }}

    - name: Publish
      env:
        CLOJARS_USER: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASS: ${{ secrets.CLOJARS_PASSWORD }}
      run: lein deploy clojars
