name: build and test

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
